### Results  - Hive

In [1]:
from data_processing import *

In [2]:
SEPARATHOR = ','
XLSX_FILE_NAME = 'hive_results.xlsx'
# FILE_PATH = '../finished_tests/final_tests_allOthello_partHex.csv'
# FILE_PATH = '../finished_tests/prarameters_tests/hive_results.csv'
FILE_PATH = '../finished_tests/hive10_part_tests.csv'

In [5]:
df, result_df, df_tournament = process_data(FILE_PATH, SEPARATHOR, 'hive', True)

Amount data before check: 146
Amount data after check: 99

In [7]:
df = read_data_of_game(FILE_PATH, SEPARATHOR, 'hive')

In [6]:
df

,game_type,player1,player2,winner,seed,game_time,other
0,hive,greedyhive_strategy,greedyhive_strategy,0,22020110,0.146894,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
1,hive,greedyhive_strategy,random_strategy,0,22020110,0.354469,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
2,hive,random_strategy,greedyhive_strategy,0,22020110,0.453334,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
3,hive,random_strategy,random_strategy,0,22020110,0.479358,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
4,hive,greedyhive_strategy,mobility_strategy,0,22020110,1.649849,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
...,...,...,...,...,...,...,...
94,hive,mctsstrategy500(evaluatehive_strategy),random_strategy,0,22020110,1109.468759,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
95,hive,mcts500,mctsstrategy500(evaluatehive_strategy),0,22020110,1112.475760,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
96,hive,random_strategy,mctsstrategy500(evaluatehive_strategy),0,22020110,1178.561536,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
97,hive,mctsrave_v2500,mctsstrategy500(evaluatehive_strategy),0,22020110,1199.192185,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
98,hive,mctsstrategy500(evaluatehive_strategy),mctsstrategy500(evaluatehive_strategy),0,22020110,1774.748618,"([((0, 0), 0), ((0, 1), 0), ((0, 1), 0), ((0, ..."

In [17]:
df.loc[df.duplicated(subset=df.columns.difference(['index','game_time','other']))]

,game_type,player1,player2,winner,seed,game_time,other
99,hive,mctsstrategy500(greedyhive_strategy),mobility_strategy,0,22020110,5410.174113,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
100,hive,mctsstrategy500(greedyhive_strategy),mobility_strategy_vs,0,22020110,5781.704147,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
101,hive,mctsstrategy500(greedyhive_strategy),greedyhive_strategy,0,22020110,6057.799105,"([(0, 0), (0, 0), (0, 0), (0, 0), ((2, 0), 0),..."
102,hive,mctsstrategy500(greedyhive_strategy),random_strategy,0,22020110,6149.621605,"([(0, 0), (0, 0), (0, 0), (0, 0), ((2, 0), 0),..."
103,hive,mctsstrategy500(greedyhive_strategy),alphabeta10,0,22020110,8460.515593,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((1, 0)..."
104,hive,mctsstrategy500(greedyhive_strategy),mctsrave500,0,22020110,8544.503634,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((1, 0)..."
105,hive,mctsstrategy500(greedyhive_strategy),mctsstrategy500(greedyhive_strategy),2,22020110,9830.649439,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
106,hive,mctsstrategy500(greedyhive_strategy),mctsrave_v2500,0,22020110,11605.715153,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
107,hive,mctsstrategy500(greedyhive_strategy),mcts500,0,22020110,11738.458116,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((1, 0)..."
108,hive,mctsstrategy500(evaluatehive_strategy),mctsstrategy500(greedyhive_strategy),0,22020110,47931.374214,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
109,hive,mctsstrategy500(greedyhive_strategy),mctsstrategy500(evaluatehive_strategy),1,22020110,50911.840282,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
110,hive,mctsstrategy500(evaluatehive_strategy),mobility_strategy_vs,0,22020110,52866.131684,"([((0, 0), 0), ((0, 1), (0, 1)), ((1, 1), (0, ..."
111,hive,mctsstrategy500(evaluatehive_strategy),greedyhive_strategy,0,22020110,53244.539204,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
112,hive,random_strategy,random_strategy,0,22020110,5.322364,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
113,hive,random_strategy,greedyhive_strategy,0,22020110,7.198142,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
114,hive,random_strategy,mobility_strategy_vs,0,22020110,240.610417,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
115,hive,random_strategy,mobility_strategy,0,22020110,120.976990,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
116,hive,random_strategy,mctsstrategy500(greedyhive_strategy),0,22020110,3574.845577,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
117,hive,mctsstrategy500(evaluatehive_strategy),alphabeta10,1,22020110,54492.529896,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
118,hive,mctsstrategy500(evaluatehive_strategy),mcts500,1,22020110,54802.622767,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
119,hive,mctsstrategy500(evaluatehive_strategy),mctsrave500,0,22020110,55816.974398,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
120,hive,mctsstrategy500(evaluatehive_strategy),mctsrave_v2500,0,22020110,57834.663527,"([((0, 0), 0), ((0, 1), 0), ((0, 1), 0), ((0, ..."
121,hive,mctsstrategy500(evaluatehive_strategy),random_strategy,0,22020110,58379.045401,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
122,hive,random_strategy,alphabeta10,0,22020110,990.414858,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
123,hive,random_strategy,mctsrave_v2500,2,22020110,4556.725306,"([(0, 0), (0, (0, 1)), ((1, 0), (0, 1)), ((1, ..."
124,hive,random_strategy,mctsrave500,0,22020110,7762.219434,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
125,hive,random_strategy,mcts500,0,22020110,8860.130308,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
126,hive,greedyhive_strategy,random_strategy,0,22020110,1.893340,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
127,hive,greedyhive_strategy,greedyhive_strategy,0,22020110,1.247761,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
128,hive,greedyhive_strategy,mobility_strategy_vs,0,22020110,161.017823,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
129,hive,greedyhive_strategy,mobility_strategy,0,22020110,16.762186,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
130,hive,greedyhive_strategy,mctsstrategy500(greedyhive_strategy),0,22020110,3814.321559,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
131,hive,greedyhive_strategy,mcts500,0,22020110,5498.222778,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
132,hive,greedyhive_strategy,mctsrave500,0,22020110,5543.703310,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
133,hive,greedyhive_strategy,mctsrave_v2500,1,22020110,5465.689896,"([(0, 0), (0, (0, 1)), ((1, 0), (0, 1)), ((1, ..."
134,hive,mctsstrategy500(evaluatehive_strategy),mctsstrategy500(evaluatehive_strategy),0,22020110,91766.232437,"([((0, 0), 0), ((0, 1), 0), ((0, 1), 0), ((0, ..."
135,hive,greedyhive_strategy,alphabeta10,0,22020110,659.701782,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
136,hive,random_strategy,mctsstrategy500(evaluatehive_strategy),0,22020110,48260.458040,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
137,hive,greedyhive_strategy,mctsstrategy500(evaluatehive_strategy),0,22020110,43497.976702,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
138,hive,mobility_strategy_vs,mctsstrategy500(greedyhive_strategy),0,22020110,5781.445468,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
139,hive,mobility_strategy_vs,mctsstrategy500(evaluatehive_strategy),0,22020110,39905.843636,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((1, 0)..."
140,hive,mobility_strategy_vs,random_strategy,0,22020110,181.268739,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
141,hive,mobility_strategy_vs,greedyhive_strategy,0,22020110,71.971781,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
142,hive,mobility_strategy_vs,mobility_strategy_vs,0,22020110,113.766639,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
143,hive,mobility_strategy_vs,mobility_strategy,0,22020110,80.471099,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
144,hive,mobility_strategy_vs,mcts500,0,22020110,6154.262567,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
145,hive,mobility_strategy_vs,mctsrave500,0,22020110,6492.876490,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."

In [18]:
get_all_games_of_player(df,'random_strategy')

,game_type,player1,player2,winner,seed,game_time,other
2,hive,random_strategy,greedyhive_strategy,0,22020110,0.453334,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
3,hive,random_strategy,random_strategy,0,22020110,0.479358,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
9,hive,random_strategy,mobility_strategy,0,22020110,3.994800,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
15,hive,random_strategy,mobility_strategy_vs,0,22020110,6.980957,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
19,hive,random_strategy,alphabeta10,0,22020110,25.182788,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
27,hive,random_strategy,mctsstrategy500(greedyhive_strategy),0,22020110,91.636080,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
31,hive,random_strategy,mctsrave_v2500,2,22020110,110.828476,"([(0, 0), (0, (0, 1)), ((1, 0), (0, 1)), ((1, ..."
63,hive,random_strategy,mctsrave500,0,22020110,197.371780,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
64,hive,random_strategy,mcts500,0,22020110,198.511033,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
96,hive,random_strategy,mctsstrategy500(evaluatehive_strategy),0,22020110,1178.561536,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
112,hive,random_strategy,random_strategy,0,22020110,5.322364,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
113,hive,random_strategy,greedyhive_strategy,0,22020110,7.198142,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
114,hive,random_strategy,mobility_strategy_vs,0,22020110,240.610417,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
115,hive,random_strategy,mobility_strategy,0,22020110,120.976990,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
116,hive,random_strategy,mctsstrategy500(greedyhive_strategy),0,22020110,3574.845577,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
122,hive,random_strategy,alphabeta10,0,22020110,990.414858,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
123,hive,random_strategy,mctsrave_v2500,2,22020110,4556.725306,"([(0, 0), (0, (0, 1)), ((1, 0), (0, 1)), ((1, ..."
124,hive,random_strategy,mctsrave500,0,22020110,7762.219434,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
125,hive,random_strategy,mcts500,0,22020110,8860.130308,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
136,hive,random_strategy,mctsstrategy500(evaluatehive_strategy),0,22020110,48260.458040,"([(0, 0), (0, 0), (0, 0), (0, (1, 0)), ((2, 0)..."
1,hive,greedyhive_strategy,random_strategy,0,22020110,0.354469,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
10,hive,mobility_strategy,random_strategy,0,22020110,2.071753,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
14,hive,mobility_strategy_vs,random_strategy,0,22020110,6.184029,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
20,hive,alphabeta10,random_strategy,0,22020110,24.068797,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
33,hive,mctsstrategy500(greedyhive_strategy),random_strategy,0,22020110,118.263417,"([(0, 0), (0, 0), (0, 0), (0, 0), ((2, 0), 0),..."
39,hive,mctsrave_v2500,random_strategy,0,22020110,123.605075,"([(0, 0), (0, (0, 1)), (0, (0, 1)), (0, (1, 1)..."
43,hive,mctsrave500,random_strategy,0,22020110,130.515868,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
49,hive,mcts500,random_strategy,0,22020110,142.712903,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
94,hive,mctsstrategy500(evaluatehive_strategy),random_strategy,0,22020110,1109.468759,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
102,hive,mctsstrategy500(greedyhive_strategy),random_strategy,0,22020110,6149.621605,"([(0, 0), (0, 0), (0, 0), (0, 0), ((2, 0), 0),..."
121,hive,mctsstrategy500(evaluatehive_strategy),random_strategy,0,22020110,58379.045401,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."
126,hive,greedyhive_strategy,random_strategy,0,22020110,1.893340,"([(0, 0), (0, 0), ((1, 0), 0), ((1, 0), 0), ((..."
140,hive,mobility_strategy_vs,random_strategy,0,22020110,181.268739,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."

In [20]:
get_games_between_two_players(df,'random_strategy', 'mcts500')

,game_type,player1,player2,winner,seed,game_time,other
64,hive,random_strategy,mcts500,0,22020110,198.511033,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
125,hive,random_strategy,mcts500,0,22020110,8860.130308,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."

In [21]:
get_all_games_between_two_players(df,'random_strategy', 'mcts500')

,game_type,player1,player2,winner,seed,game_time,other
64,hive,random_strategy,mcts500,0,22020110,198.511033,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
125,hive,random_strategy,mcts500,0,22020110,8860.130308,"([(0, 0), (0, 0), (0, 0), (0, 0), ((1, 0), 0),..."
49,hive,mcts500,random_strategy,0,22020110,142.712903,"([((0, 0), 0), ((0, 1), 0), ((1, 1), 0), ((1, ..."

In [28]:
from start_async_test import create_tests

ModuleNotFoundError: No module named 'games'

In [14]:
print(f"Amount data before check: {len(df)}")
df2 = df.drop_duplicates(subset=df.columns.difference(['index','game_time','other']))
print(f"Amount data before check: {len(df2)}")

Amount data before check: 146
Amount data before check: 99

In [13]:
df.columns.difference(['index','game_time','other'])

Index(['game_type', 'player1', 'player2', 'seed', 'winner'], dtype='object')

In [4]:
result_df[:6]

,wins,draws,defeats,avg game time,score,win%,draws%,defeats%,no games
greedyhive_strategy,48,42,1,2394.08,69.0,52.747253,46.153846,1.098901,91
evaluatehive_strategy,45,45,4,7753.87,67.5,47.872340,47.872340,4.255319,94
random_strategy,33,53,3,2071.77,59.5,37.078652,59.550562,3.370787,89
mobility_strategy_vs,20,62,8,6813.71,51.0,22.222222,68.888889,8.888889,90
mobility_strategy,0,89,4,4471.71,44.5,0.000000,95.698925,4.301075,93
alphabeta4,20,17,58,16232.78,28.5,21.052632,17.894737,61.052632,95

In [5]:
df_tournament.iloc[:6,:6]

,greedyhive_strategy,evaluatehive_strategy,random_strategy,mobility_strategy_vs,mobility_strategy,alphabeta4
greedyhive_strategy,0-4-1,0-5-0,1-4-0,2-3-0,0-5-0,5-0-0
evaluatehive_strategy,0-4-1,0-5-0,0-5-0,0-5-0,0-5-0,5-0-0
random_strategy,0-3-2,0-5-0,0-5-0,0-5-0,1-4-0,5-0-0
mobility_strategy_vs,0-5-0,0-0-5,0-4-0,0-5-0,0-5-0,5-0-0
mobility_strategy,0-5-0,0-5-0,0-5-0,0-5-0,0-5-0,0-5-0
alphabeta4,0-0-5,0-0-5,0-2-3,0-5-0,0-5-0,5-0-0

In [18]:
writer = pd.ExcelWriter('hive_results.xlsx', engine='xlsxwriter')
result_df.to_excel(writer, sheet_name='result_df')
df_tournament.to_excel(writer, sheet_name='df_tournament')
writer.save()

In [6]:
df.sample(3)

,game_type,player1,player2,winner,seed,game_time
113,hive,mobility_strategy,mobility_strategy_vs,0,22025002,1040.219863
181,hive,alphabeta4,alphabeta4,1,22025002,1612.397125
255,hive,alphabeta4,mobility_strategy,0,22025003,3361.240698

In [ ]:
get_all_games_of_player(df, random_strategy)

In [ ]:
import pandas as pd

In [18]:
df = pd.read_csv(FILE_PATH, sep=SEPARATHOR, header=None)

df.columns = ['game_type','player1','player2','winner','seed','game_time']

df = df[df['game_type']=='hive']

df['time_min']=df['game_time']/(60)
df['time_h']=df['game_time']/(60*60)
df['time_day']=df['game_time']/(24*60*60)

In [22]:
df.groupby(by=['player1'], as_index=True).agg({'game_time':'count',
'time_min': 'mean',
'time_h': 'mean',
'time_day': 'mean'})

,game_time,time_min,time_h,time_day
player1,,,,
alphabeta10,39,176.429899,2.940498,0.122521
alphabeta4,49,203.910029,3.398500,0.141604
alphabeta6,49,168.338651,2.805644,0.116902
alphabeta8,49,197.691221,3.294854,0.137286
evaluatehive_strategy,49,197.796499,3.296608,0.137359
greedyhive_strategy,45,12.535601,0.208927,0.008705
mcts1000,6,2383.220716,39.720345,1.655014
mctsrave1000,10,2192.571274,36.542855,1.522619
mctsstrategy1000(greedyhive_strategy),1,1513.667128,25.227785,1.051158
mobility_strategy,47,89.406326,1.490105,0.062088
mobility_strategy_vs,45,99.230551,1.653843,0.068910
random_strategy,45,24.603526,0.410059,0.017086

In [23]:
df.groupby(by=['player2'], as_index=True).agg({'game_time':'count',
'time_min': 'mean',
'time_h': 'mean',
'time_day': 'mean'})

,game_time,time_min,time_h,time_day
player2,,,,
alphabeta10,47,129.305782,2.155096,0.089796
alphabeta4,46,315.105168,5.251753,0.218823
alphabeta6,46,289.240935,4.820682,0.200862
alphabeta8,47,133.379228,2.222987,0.092624
evaluatehive_strategy,45,40.410098,0.673502,0.028063
greedyhive_strategy,46,62.395673,1.039928,0.043330
mcts1000,3,2009.364398,33.489407,1.395392
mctsrave2000,1,1392.186882,23.203115,0.966796
mctsstrategy1000(greedyhive_strategy),18,1716.872589,28.614543,1.192273
mobility_strategy,46,51.353648,0.855894,0.035662
mobility_strategy_vs,45,116.858159,1.947636,0.081151
random_strategy,44,40.855535,0.680926,0.028372